spring.application.name=course-ms

# config-server
spring.config.import=optional:configserver:http://localhost:8888

#server.port=8082

#spring.datasource.url=jdbc:postgresql://localhost:5432/coursedb
#spring.datasource.username=postgres
#spring.datasource.password=1
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
#management.endpoints.web.base-path=/actuator

#spring.cloud.consul.host=localhost
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.enabled=true
#spring.cloud.consul.discovery.register=true
#spring.cloud.consul.discovery.prefer-ip-address=true
#spring.cloud.consul.discovery.server-name=${spring.application.name}:${server.port}
#spring.cloud.consul.discovery.health-check-path=/actuator/health
#spring.cloud.consul.discovery.health-check-interval=20s